__asm__(".intel_syntax noprefix\n"
        ".section .data\n"
        ".global daemon_start\n"
        ".type   daemon_start, @object\n"
        ".align  16\n"
        "daemon_start:\n"
        ".incbin \"../../../bin/daemon.elf\"\n"
        "daemon_end:\n"
        ".global daemon_size\n"
        ".type   daemon_size, @object\n"
        ".align  4\n"
        "daemon_size:\n"
        ".int    daemon_end - daemon_start\n"

        ".global util_start\n"
        ".type   util_start, @object\n"
        ".align  16\n"
        "util_start:\n"
        ".incbin \"../../../bin/util.elf\"\n"
        "util_end:\n"
        ".global util_size\n"
        ".type   util_size, @object\n"
        ".align  4\n"
        "util_size:\n"
        ".int    util_end - util_start\n"

        ".global store_png_start\n"
        ".type   store_png_start, @object\n"
        ".align  16\n"
        "store_png_start:\n"
        ".incbin \"../../../bootstrapper/assets/store.png\"\n"
        "store_png_end:\n"
        ".global store_png_size\n"
        ".type   store_png_size, @object\n"
        ".align  4\n"
        "store_png_size:\n"
        ".int    store_png_end - store_png_start\n"

        ".global sicon_start\n"
        ".type   sicon_start, @object\n"
        ".align  16\n"
        "sicon_start:\n"
        ".incbin \"../../../bootstrapper/assets/pizzahen_sicon.png\"\n"
        "sicon_end:\n"
        ".global sicon_size\n"
        ".type   sicon_size, @object\n"
        ".align  4\n"
        "sicon_size:\n"
        ".int    sicon_end - sicon_start\n"
       
        ".global webman_icon_start\n"
        ".type   webman_icon_start,"
        "@object\n"
        ".align  16\n"
        "webman_icon_start:\n"
        ".incbin \"../../../bootstrapper/assets/webMAN.png\"\n"
        "webman_icon_end:\n"
        ".global webman_icon_size\n"
        ".type   webman_icon_size, @object\n"
        ".align  4\n"
        "webman_icon_size:\n"
        ".int    webman_icon_end - webman_icon_start\n"

        ".global itemzflow_theme_start\n"
        ".type   itemzflow_theme_start, @object\n"
        ".align  16\n"
        "itemzflow_theme_start:\n"
        ".incbin \"../../../bootstrapper/assets/itemzflow_pizzahen_background.png\"\n"
        "itemzflow_theme_end:\n"
        ".global itemzflow_theme_size\n"
        ".type   itemzflow_theme_size, @object\n"
        ".align  4\n"
        "itemzflow_theme_size:\n"
        ".int    itemzflow_theme_end - itemzflow_theme_start\n"

    ".global kstuff_start\n"
    ".type   kstuff_start, @object\n"
    ".align  16\n"
    "kstuff_start:\n"
    ".incbin \"../../../bootstrapper/assets/kstuff.elf\"\n"
    "kstuff_end:\n"
    ".global kstuff_size\n"
    ".type  kstuff_size, @object\n"
    ".align  4\n"
    "kstuff_size:\n"
    ".int    kstuff_end - kstuff_start\n"



    ".global kstuff_dr_start\n"
    ".type   kstuff_dr_start, @object\n"
    ".align  16\n"
    "kstuff_dr_start:\n"
    ".incbin \"../../../bootstrapper/assets/kstuff-dr-1.2-test1.elf\"\n"
    "kstuff_dr_end:\n"
    ".global kstuff_dr_size\n"
    ".type  kstuff_dr_size, @object\n"
    ".align  4\n"
    "kstuff_dr_size:\n"
    ".int    kstuff_dr_end - kstuff_dr_start\n"

    ".global websrv_start\n"
    ".type   websrv_start, @object\n"
    ".align  16\n"
    "websrv_start:\n"
    ".incbin \"../../../bootstrapper/assets/websrv-ps5.elf\"\n"
    "websrv_end:\n"
    ".global websrv_size\n"
    ".type  websrv_size, @object\n"
    ".align  4\n"
    "websrv_size:\n"
    ".int    websrv_end - websrv_start\n"

    ".global selector_js_start\n"
    ".type   selector_js_start, @object\n"
    ".align  16\n"
    "selector_js_start:\n"
    ".incbin \"../../../bootstrapper/assets/kstuff_selector.js\"\n"
    "selector_js_end:\n"
    ".global selector_js_size\n"
    ".type  selector_js_size, @object\n"
    ".align  4\n"
    "selector_js_size:\n"
    ".int    selector_js_end - selector_js_start\n"

    ".global selector_html_start\n"
    ".type   selector_html_start, @object\n"
    ".align  16\n"
    "selector_html_start:\n"
    ".incbin \"../../../bootstrapper/assets/kstuff_selector.html\"\n"
    "selector_html_end:\n"
    ".global selector_html_size\n"
    ".type  selector_html_size, @object\n"
    ".align  4\n"
    "selector_html_size:\n"
    ".int    selector_html_end - selector_html_start\n"

    ".global selector_icon_start\n"
    ".type   selector_icon_start, @object\n"
    ".align  16\n"
    "selector_icon_start:\n"
    ".incbin \"../../../bootstrapper/assets/kstuff_selector_icon.png\"\n"
    "selector_icon_end:\n"
    ".global selector_icon_size\n"
    ".type  selector_icon_size, @object\n"
    ".align  4\n"
    "selector_icon_size:\n"
    ".int    selector_icon_end - selector_icon_start\n"

    ".global selector_action_start\n"
    ".type   selector_action_start, @object\n"
    ".align  16\n"
    "selector_action_start:\n"
    ".incbin \"../../../bin/pizzahen-kstuff-select.elf\"\n"
    "selector_action_end:\n"
    ".global selector_action_size\n"
    ".type  selector_action_size, @object\n"
    ".align  4\n"
    "selector_action_size:\n"
    ".int    selector_action_end - selector_action_start\n"

    ".global toolbox_action_start\n"
    ".type   toolbox_action_start, @object\n"
    ".align  16\n"
    "toolbox_action_start:\n"
    ".incbin \"../../../bin/pizzahen-toolbox-open.elf\"\n"
    "toolbox_action_end:\n"
    ".global toolbox_action_size\n"
    ".type  toolbox_action_size, @object\n"
    ".align  4\n"
    "toolbox_action_size:\n"
    ".int    toolbox_action_end - toolbox_action_start\n"

    ".global shadowmount_start\n"
    ".type   shadowmount_start, @object\n"
    ".align  16\n"
    "shadowmount_start:\n"
    ".incbin \"../../../bootstrapper/assets/shadowmountplus.elf\"\n"
    "shadowmount_end:\n"
    ".global shadowmount_size\n"
    ".type  shadowmount_size, @object\n"
    ".align  4\n"
    "shadowmount_size:\n"
    ".int    shadowmount_end - shadowmount_start\n"

    ".global ftpsrv_start\n"
    ".type   ftpsrv_start, @object\n"
    ".align  16\n"
    "ftpsrv_start:\n"
    ".incbin \"../../../bootstrapper/assets/ftpsrv-ps5.elf\"\n"
    "ftpsrv_end:\n"
    ".global ftpsrv_size\n"
    ".type  ftpsrv_size, @object\n"
    ".align  4\n"
    "ftpsrv_size:\n"
    ".int    ftpsrv_end - ftpsrv_start\n"

    ".global ps5debug_ng_start\n"
    ".type   ps5debug_ng_start, @object\n"
    ".align  16\n"
    "ps5debug_ng_start:\n"
    ".incbin \"../../../bootstrapper/assets/ps5debug-NG_v1.3.0.elf\"\n"
    "ps5debug_ng_end:\n"
    ".global ps5debug_ng_size\n"
    ".type  ps5debug_ng_size, @object\n"
    ".align  4\n"
    "ps5debug_ng_size:\n"
    ".int    ps5debug_ng_end - ps5debug_ng_start\n"

    ".global toolbox_shortcut_icon_start\n"
    ".type   toolbox_shortcut_icon_start, @object\n"
    ".align  16\n"
    "toolbox_shortcut_icon_start:\n"
    ".incbin \"../../../bootstrapper/assets/pizzahen_toolbox_icon.png\"\n"
    "toolbox_shortcut_icon_end:\n"
    ".global toolbox_shortcut_icon_size\n"
    ".type  toolbox_shortcut_icon_size, @object\n"
    ".align  4\n"
    "toolbox_shortcut_icon_size:\n"
    ".int    toolbox_shortcut_icon_end - toolbox_shortcut_icon_start\n"

    ".global toolbox_shortcut_param_start\n"
    ".type   toolbox_shortcut_param_start, @object\n"
    ".align  16\n"
    "toolbox_shortcut_param_start:\n"
    ".incbin \"../../../bootstrapper/assets/toolbox_shortcut_param.json\"\n"
    "toolbox_shortcut_param_end:\n"
    ".global toolbox_shortcut_param_size\n"
    ".type  toolbox_shortcut_param_size, @object\n"
    ".align  4\n"
    "toolbox_shortcut_param_size:\n"
    ".int    toolbox_shortcut_param_end - toolbox_shortcut_param_start\n"

    ".global toolbox_launcher_html_start\n"
    ".type   toolbox_launcher_html_start, @object\n"
    ".align  16\n"
    "toolbox_launcher_html_start:\n"
    ".incbin \"../../../bootstrapper/assets/toolbox_launcher.html\"\n"
    "toolbox_launcher_html_end:\n"
    ".global toolbox_launcher_html_size\n"
    ".type  toolbox_launcher_html_size, @object\n"
    ".align  4\n"
    "toolbox_launcher_html_size:\n"
    ".int    toolbox_launcher_html_end - toolbox_launcher_html_start\n"

    ".global fps_prx_start\n"
    ".type   fps_prx_start, @object\n"
    ".align  16\n"
    "fps_prx_start:\n"
    ".incbin \"../../../bootstrapper/assets/fps.prx\"\n"
    "fps_prx_end:\n"
    ".global fps_prx_size\n"
    ".type  fps_prx_size, @object\n"
    ".align  4\n"
    "fps_prx_size:\n"
    ".int    fps_prx_end - fps_prx_start\n"
);
