__asm__(".intel_syntax noprefix\n"
        ".section .data\n"
        ".global daemon_start\n"
        ".type   daemon_start, @object\n"
        ".align  16\n"
        "daemon_start:\n"
        ".incbin \"../../../bin/daemon.elf\"\n"
        "daemon_end:\n"
        ".global daemon_size\n"
        ".type   daemon_size, @object\n"
        ".align  4\n"
        "daemon_size:\n"
        ".int    daemon_end - daemon_start\n"

        ".global util_start\n"
        ".type   util_start, @object\n"
        ".align  16\n"
        "util_start:\n"
        ".incbin \"../../../bin/util.elf\"\n"
        "util_end:\n"
        ".global util_size\n"
        ".type   util_size, @object\n"
        ".align  4\n"
        "util_size:\n"
        ".int    util_end - util_start\n"

        ".global store_png_start\n"
        ".type   store_png_start, @object\n"
        ".align  16\n"
        "store_png_start:\n"
        ".incbin \"../../../bootstrapper/assets/store.png\"\n"
        "store_png_end:\n"
        ".global store_png_size\n"
        ".type   store_png_size, @object\n"
        ".align  4\n"
        "store_png_size:\n"
        ".int    store_png_end - store_png_start\n"

        ".global sicon_start\n"
        ".type   sicon_start, @object\n"
        ".align  16\n"
        "sicon_start:\n"
        ".incbin \"../../../bootstrapper/assets/pizzahen_sicon.png\"\n"
        "sicon_end:\n"
        ".global sicon_size\n"
        ".type   sicon_size, @object\n"
        ".align  4\n"
        "sicon_size:\n"
        ".int    sicon_end - sicon_start\n"
       
        ".global webman_icon_start\n"
        ".type   webman_icon_start,"
        "@object\n"
        ".align  16\n"
        "webman_icon_start:\n"
        ".incbin \"../../../bootstrapper/assets/webMAN.png\"\n"
        "webman_icon_end:\n"
        ".global webman_icon_size\n"
        ".type   webman_icon_size, @object\n"
        ".align  4\n"
        "webman_icon_size:\n"
        ".int    webman_icon_end - webman_icon_start\n"

        ".global itemzflow_theme_start\n"
        ".type   itemzflow_theme_start, @object\n"
        ".align  16\n"
        "itemzflow_theme_start:\n"
        ".incbin \"../../../bootstrapper/assets/itemzflow_pizzahen_background.png\"\n"
        "itemzflow_theme_end:\n"
        ".global itemzflow_theme_size\n"
        ".type   itemzflow_theme_size, @object\n"
        ".align  4\n"
        "itemzflow_theme_size:\n"
        ".int    itemzflow_theme_end - itemzflow_theme_start\n"

    ".global kstuff_start\n"
    ".type   kstuff_start, @object\n"
    ".align  16\n"
    "kstuff_start:\n"
    ".incbin \"../../../bootstrapper/assets/kstuff.elf\"\n"
    "kstuff_end:\n"
    ".global kstuff_size\n"
    ".type  kstuff_size, @object\n"
    ".align  4\n"
    "kstuff_size:\n"
    ".int    kstuff_end - kstuff_start\n"



    ".global kstuff_base_start\n"
    ".type   kstuff_base_start, @object\n"
    ".align  16\n"
    "kstuff_base_start:\n"
    ".incbin \"../../../bootstrapper/assets/kstuff-base-1.6.7.elf\"\n"
    "kstuff_base_end:\n"
    ".global kstuff_base_size\n"
    ".type  kstuff_base_size, @object\n"
    ".align  4\n"
    "kstuff_base_size:\n"
    ".int    kstuff_base_end - kstuff_base_start\n"

    ".global kstuff_dr_start\n"
    ".type   kstuff_dr_start, @object\n"
    ".align  16\n"
    "kstuff_dr_start:\n"
    ".incbin \"../../../bootstrapper/assets/kstuff-dr-1.2-test1.elf\"\n"
    "kstuff_dr_end:\n"
    ".global kstuff_dr_size\n"
    ".type  kstuff_dr_size, @object\n"
    ".align  4\n"
    "kstuff_dr_size:\n"
    ".int    kstuff_dr_end - kstuff_dr_start\n"

    ".global websrv_start\n"
    ".type   websrv_start, @object\n"
    ".align  16\n"
    "websrv_start:\n"
    ".incbin \"../../../bootstrapper/assets/websrv-ps5.elf\"\n"
    "websrv_end:\n"
    ".global websrv_size\n"
    ".type  websrv_size, @object\n"
    ".align  4\n"
    "websrv_size:\n"
    ".int    websrv_end - websrv_start\n"

    ".global selector_js_start\n"
    ".type   selector_js_start, @object\n"
    ".align  16\n"
    "selector_js_start:\n"
    ".incbin \"../../../bootstrapper/assets/kstuff_selector.js\"\n"
    "selector_js_end:\n"
    ".global selector_js_size\n"
    ".type  selector_js_size, @object\n"
    ".align  4\n"
    "selector_js_size:\n"
    ".int    selector_js_end - selector_js_start\n"

    ".global selector_html_start\n"
    ".type   selector_html_start, @object\n"
    ".align  16\n"
    "selector_html_start:\n"
    ".incbin \"../../../bootstrapper/assets/kstuff_selector.html\"\n"
    "selector_html_end:\n"
    ".global selector_html_size\n"
    ".type  selector_html_size, @object\n"
    ".align  4\n"
    "selector_html_size:\n"
    ".int    selector_html_end - selector_html_start\n"

    ".global shadow_selector_html_start\n"
    ".type   shadow_selector_html_start, @object\n"
    ".align  16\n"
    "shadow_selector_html_start:\n"
    ".incbin \"../../../bootstrapper/assets/shadowmount_selector.html\"\n"
    "shadow_selector_html_end:\n"
    ".global shadow_selector_html_size\n"
    ".type  shadow_selector_html_size, @object\n"
    ".align  4\n"
    "shadow_selector_html_size:\n"
    ".int    shadow_selector_html_end - shadow_selector_html_start\n"

    ".global selector_icon_start\n"
    ".type   selector_icon_start, @object\n"
    ".align  16\n"
    "selector_icon_start:\n"
    ".incbin \"../../../bootstrapper/assets/kstuff_selector_icon.png\"\n"
    "selector_icon_end:\n"
    ".global selector_icon_size\n"
    ".type  selector_icon_size, @object\n"
    ".align  4\n"
    "selector_icon_size:\n"
    ".int    selector_icon_end - selector_icon_start\n"

    ".global selector_action_start\n"
    ".type   selector_action_start, @object\n"
    ".align  16\n"
    "selector_action_start:\n"
    ".incbin \"../../../bin/pizzahen-kstuff-select.elf\"\n"
    "selector_action_end:\n"
    ".global selector_action_size\n"
    ".type  selector_action_size, @object\n"
    ".align  4\n"
    "selector_action_size:\n"
    ".int    selector_action_end - selector_action_start\n"

    ".global shadow_selector_action_start\n"
    ".type   shadow_selector_action_start, @object\n"
    ".align  16\n"
    "shadow_selector_action_start:\n"
    ".incbin \"../../../bin/pizzahen-shadowmount-select.elf\"\n"
    "shadow_selector_action_end:\n"
    ".global shadow_selector_action_size\n"
    ".type  shadow_selector_action_size, @object\n"
    ".align  4\n"
    "shadow_selector_action_size:\n"
    ".int    shadow_selector_action_end - shadow_selector_action_start\n"

    ".global toolbox_action_start\n"
    ".type   toolbox_action_start, @object\n"
    ".align  16\n"
    "toolbox_action_start:\n"
    ".incbin \"../../../bin/pizzahen-toolbox-open.elf\"\n"
    "toolbox_action_end:\n"
    ".global toolbox_action_size\n"
    ".type  toolbox_action_size, @object\n"
    ".align  4\n"
    "toolbox_action_size:\n"
    ".int    toolbox_action_end - toolbox_action_start\n"

    ".global toolbox_api_start\n"
    ".type   toolbox_api_start, @object\n"
    ".align  16\n"
    "toolbox_api_start:\n"
    ".incbin \"../../../bin/pizzahen-api.elf\"\n"
    "toolbox_api_end:\n"
    ".global toolbox_api_size\n"
    ".type  toolbox_api_size, @object\n"
    ".align  4\n"
    "toolbox_api_size:\n"
    ".int    toolbox_api_end - toolbox_api_start\n"

    ".global shadowmount_start\n"
    ".type   shadowmount_start, @object\n"
    ".align  16\n"
    "shadowmount_start:\n"
    ".incbin \"../../../bootstrapper/assets/shadowmountplus.elf\"\n"
    "shadowmount_end:\n"
    ".global shadowmount_size\n"
    ".type  shadowmount_size, @object\n"
    ".align  4\n"
    "shadowmount_size:\n"
    ".int    shadowmount_end - shadowmount_start\n"

    ".global apr_emu_updater_start\n"
    ".type   apr_emu_updater_start, @object\n"
    ".align  16\n"
    "apr_emu_updater_start:\n"
    ".incbin \"../../../bootstrapper/assets/apr_emu_updater.elf\"\n"
    "apr_emu_updater_end:\n"
    ".global apr_emu_updater_size\n"
    ".type  apr_emu_updater_size, @object\n"
    ".align  4\n"
    "apr_emu_updater_size:\n"
    ".int    apr_emu_updater_end - apr_emu_updater_start\n"

    ".global backpork_start\n"
    ".type   backpork_start, @object\n"
    ".align  16\n"
    "backpork_start:\n"
    ".incbin \"../../../bootstrapper/assets/ps5-backpork.elf\"\n"
    "backpork_end:\n"
    ".global backpork_size\n"
    ".type  backpork_size, @object\n"
    ".align  4\n"
    "backpork_size:\n"
    ".int    backpork_end - backpork_start\n"

    ".global garlic_savemgr_start\n"
    ".type   garlic_savemgr_start, @object\n"
    ".align  16\n"
    "garlic_savemgr_start:\n"
    ".incbin \"../../../bootstrapper/assets/garlic-savemgr.elf\"\n"
    "garlic_savemgr_end:\n"
    ".global garlic_savemgr_size\n"
    ".type  garlic_savemgr_size, @object\n"
    ".align  4\n"
    "garlic_savemgr_size:\n"
    ".int    garlic_savemgr_end - garlic_savemgr_start\n"

    ".global fw_spoof_start\n"
    ".type   fw_spoof_start, @object\n"
    ".align  16\n"
    "fw_spoof_start:\n"
    ".incbin \"../../../bootstrapper/assets/ps5-fw-spoof_v26616621599.elf\"\n"
    "fw_spoof_end:\n"
    ".global fw_spoof_size\n"
    ".type  fw_spoof_size, @object\n"
    ".align  4\n"
    "fw_spoof_size:\n"
    ".int    fw_spoof_end - fw_spoof_start\n"

    ".global airpsx_start\n"
    ".type   airpsx_start, @object\n"
    ".align  16\n"
    "airpsx_start:\n"
    ".incbin \"../../../bootstrapper/assets/airpsx_v0.19.elf\"\n"
    "airpsx_end:\n"
    ".global airpsx_size\n"
    ".type  airpsx_size, @object\n"
    ".align  4\n"
    "airpsx_size:\n"
    ".int    airpsx_end - airpsx_start\n"

    ".global ps5upload_start\n"
    ".type   ps5upload_start, @object\n"
    ".align  16\n"
    "ps5upload_start:\n"
    ".incbin \"../../../bootstrapper/assets/ps5upload_v5.4.8.elf\"\n"
    "ps5upload_end:\n"
    ".global ps5upload_size\n"
    ".type  ps5upload_size, @object\n"
    ".align  4\n"
    "ps5upload_size:\n"
    ".int    ps5upload_end - ps5upload_start\n"

    ".global np_fake_signin_start\n"
    ".type   np_fake_signin_start, @object\n"
    ".align  16\n"
    "np_fake_signin_start:\n"
    ".incbin \"../../../bootstrapper/assets/np-fake-signin_v1.3.elf\"\n"
    "np_fake_signin_end:\n"
    ".global np_fake_signin_size\n"
    ".type  np_fake_signin_size, @object\n"
    ".align  4\n"
    "np_fake_signin_size:\n"
    ".int    np_fake_signin_end - np_fake_signin_start\n"

    ".global wkali_start\n"
    ".type   wkali_start, @object\n"
    ".align  16\n"
    "wkali_start:\n"
    ".incbin \"../../../bootstrapper/assets/webkit-autoloader-installer_v0.4.0-pre-00e1028.elf\"\n"
    "wkali_end:\n"
    ".global wkali_size\n"
    ".type  wkali_size, @object\n"
    ".align  4\n"
    "wkali_size:\n"
    ".int    wkali_end - wkali_start\n"

    ".global app_dumper_start\n"
    ".type   app_dumper_start, @object\n"
    ".align  16\n"
    "app_dumper_start:\n"
    ".incbin \"../../../bootstrapper/assets/ps5-app-dumper_v1.11.elf\"\n"
    "app_dumper_end:\n"
    ".global app_dumper_size\n"
    ".type  app_dumper_size, @object\n"
    ".align  4\n"
    "app_dumper_size:\n"
    ".int    app_dumper_end - app_dumper_start\n"

    ".global game_compressor_start\n"
    ".type   game_compressor_start, @object\n"
    ".align  16\n"
    "game_compressor_start:\n"
    ".incbin \"../../../bootstrapper/assets/game-compressor.elf\"\n"
    "game_compressor_end:\n"
    ".global game_compressor_size\n"
    ".type  game_compressor_size, @object\n"
    ".align  4\n"
    "game_compressor_size:\n"
    ".int    game_compressor_end - game_compressor_start\n"


    ".global web_file_manager_start\n"
    ".type   web_file_manager_start, @object\n"
    ".align  16\n"
    "web_file_manager_start:\n"
    ".incbin \"../../../bootstrapper/assets/web-file-mgr.elf\"\n"
    "web_file_manager_end:\n"
    ".global web_file_manager_size\n"
    ".type  web_file_manager_size, @object\n"
    ".align  4\n"
    "web_file_manager_size:\n"
    ".int    web_file_manager_end - web_file_manager_start\n"

    ".global linux_loader_start\n"
    ".type   linux_loader_start, @object\n"
    ".align  16\n"
    "linux_loader_start:\n"
    ".incbin \"../../../bootstrapper/assets/ps5-linux-loader.elf\"\n"
    "linux_loader_end:\n"
    ".global linux_loader_size\n"
    ".type  linux_loader_size, @object\n"
    ".align  4\n"
    "linux_loader_size:\n"
    ".int    linux_loader_end - linux_loader_start\n"

    ".global pegasus_dl_start\n"
    ".type   pegasus_dl_start, @object\n"
    ".align  16\n"
    "pegasus_dl_start:\n"
    ".incbin \"../../../bootstrapper/assets/pegasus-dl.elf\"\n"
    "pegasus_dl_end:\n"
    ".global pegasus_dl_size\n"
    ".type  pegasus_dl_size, @object\n"
    ".align  4\n"
    "pegasus_dl_size:\n"
    ".int    pegasus_dl_end - pegasus_dl_start\n"

    ".global spectrum_library_start\n"
    ".type   spectrum_library_start, @object\n"
    ".align  16\n"
    "spectrum_library_start:\n"
    ".incbin \"../../../bootstrapper/assets/Spectrum-Library.elf\"\n"
    "spectrum_library_end:\n"
    ".global spectrum_library_size\n"
    ".type  spectrum_library_size, @object\n"
    ".align  4\n"
    "spectrum_library_size:\n"
    ".int    spectrum_library_end - spectrum_library_start\n"

    ".global remote_play_start\n"
    ".type   remote_play_start, @object\n"
    ".align  16\n"
    "remote_play_start:\n"
    ".incbin \"../../../bootstrapper/assets/rp-get-pin.elf\"\n"
    "remote_play_end:\n"
    ".global remote_play_size\n"
    ".type  remote_play_size, @object\n"
    ".align  4\n"
    "remote_play_size:\n"
    ".int    remote_play_end - remote_play_start\n"

    /* R7.25 optional media-player store: exact user-supplied ELFs.
       These are embedded into the PIZZA HEN builtin store only; they are NOT
       published to /data/PIZZA_HEN/payloads until the user presses INSTALL. */
    ".global optional_prospero_start\n"
    ".type   optional_prospero_start, @object\n"
    ".align  16\n"
    "optional_prospero_start:\n"
    ".incbin \"../../../bootstrapper/assets/ProsperoPlayer_v1.0.elf\"\n"
    "optional_prospero_end:\n"
    ".global optional_prospero_size\n"
    ".type  optional_prospero_size, @object\n"
    ".align  4\n"
    "optional_prospero_size:\n"
    ".int    optional_prospero_end - optional_prospero_start\n"

    ".global optional_psplay_start\n"
    ".type   optional_psplay_start, @object\n"
    ".align  16\n"
    "optional_psplay_start:\n"
    ".incbin \"../../../bootstrapper/assets/PS-Play_v2.1.elf\"\n"
    "optional_psplay_end:\n"
    ".global optional_psplay_size\n"
    ".type  optional_psplay_size, @object\n"
    ".align  4\n"
    "optional_psplay_size:\n"
    ".int    optional_psplay_end - optional_psplay_start\n"

    ".global optional_bfplayer_start\n"
    ".type   optional_bfplayer_start, @object\n"
    ".align  16\n"
    "optional_bfplayer_start:\n"
    ".incbin \"../../../bootstrapper/assets/BFplayer-standalone_v0.1.0-alpha.44.elf\"\n"
    "optional_bfplayer_end:\n"
    ".global optional_bfplayer_size\n"
    ".type  optional_bfplayer_size, @object\n"
    ".align  4\n"
    "optional_bfplayer_size:\n"
    ".int    optional_bfplayer_end - optional_bfplayer_start\n"

    /* R7.25.2.2 DNS tools: exact user-supplied ELF bytes. */
    ".global chukei_dns_start\n"
    ".type   chukei_dns_start, @object\n"
    ".align  16\n"
    "chukei_dns_start:\n"
    ".incbin \"../../../bootstrapper/assets/Chukei_DNS_v0.9.0.elf\"\n"
    "chukei_dns_end:\n"
    ".global chukei_dns_size\n"
    ".type  chukei_dns_size, @object\n"
    ".align  4\n"
    "chukei_dns_size:\n"
    ".int    chukei_dns_end - chukei_dns_start\n"

    ".global nanodns_start\n"
    ".type   nanodns_start, @object\n"
    ".align  16\n"
    "nanodns_start:\n"
    ".incbin \"../../../bootstrapper/assets/nanoDNS_v0.4.elf\"\n"
    "nanodns_end:\n"
    ".global nanodns_size\n"
    ".type  nanodns_size, @object\n"
    ".align  4\n"
    "nanodns_size:\n"
    ".int    nanodns_end - nanodns_start\n"

    /* R7.25.2.5 Themes Avatar: PIZZA web-only derived variants. */
    /* R7.25.2.7: exact user-supplied service ELFs. No binary patching. */
    ".global unrar_ps5_start\n"
    ".type   unrar_ps5_start, @object\n"
    ".align  16\n"
    "unrar_ps5_start:\n"
    ".incbin \"../../../bootstrapper/assets/unrar-ps5_v1.4.0.elf\"\n"
    "unrar_ps5_end:\n"
    ".global unrar_ps5_size\n"
    ".type  unrar_ps5_size, @object\n"
    ".align  4\n"
    "unrar_ps5_size:\n"
    ".int    unrar_ps5_end - unrar_ps5_start\n"

    ".global ps_game_state_start\n"
    ".type   ps_game_state_start, @object\n"
    ".align  16\n"
    "ps_game_state_start:\n"
    ".incbin \"../../../bootstrapper/assets/PS_Game_State_Lib_v0.1.elf\"\n"
    "ps_game_state_end:\n"
    ".global ps_game_state_size\n"
    ".type  ps_game_state_size, @object\n"
    ".align  4\n"
    "ps_game_state_size:\n"
    ".int    ps_game_state_end - ps_game_state_start\n"

    ".global ghostpad_start\n"
    ".type   ghostpad_start, @object\n"
    ".align  16\n"
    "ghostpad_start:\n"
    ".incbin \"../../../bootstrapper/assets/Ghostpad_v1.0.0.elf\"\n"
    "ghostpad_end:\n"
    ".global ghostpad_size\n"
    ".type  ghostpad_size, @object\n"
    ".align  4\n"
    "ghostpad_size:\n"
    ".int    ghostpad_end - ghostpad_start\n"

    ".global ghostcontrol_start\n"
    ".type   ghostcontrol_start, @object\n"
    ".align  16\n"
    "ghostcontrol_start:\n"
    ".incbin \"../../../bootstrapper/assets/Ghostcontrol-PS5-USB-Controller-Patcher_v1.0.5.elf\"\n"
    "ghostcontrol_end:\n"
    ".global ghostcontrol_size\n"
    ".type  ghostcontrol_size, @object\n"
    ".align  4\n"
    "ghostcontrol_size:\n"
    ".int    ghostcontrol_end - ghostcontrol_start\n"

    ".global ps_discord_start\n"
    ".type   ps_discord_start, @object\n"
    ".align  16\n"
    "ps_discord_start:\n"
    ".incbin \"../../../bootstrapper/assets/PS-DiscordPresence_v0.01.elf\"\n"
    "ps_discord_end:\n"
    ".global ps_discord_size\n"
    ".type  ps_discord_size, @object\n"
    ".align  4\n"
    "ps_discord_size:\n"
    ".int    ps_discord_end - ps_discord_start\n"

    ".global custom_tool_manager_start\n"
    ".type   custom_tool_manager_start, @object\n"
    ".align  16\n"
    "custom_tool_manager_start:\n"
    ".incbin \"../../../bootstrapper/assets/PS5-Custom-Tool-Manager-_vCustom-pizza-web-only.elf\"\n"
    "custom_tool_manager_end:\n"
    ".global custom_tool_manager_size\n"
    ".type  custom_tool_manager_size, @object\n"
    ".align  4\n"
    "custom_tool_manager_size:\n"
    ".int    custom_tool_manager_end - custom_tool_manager_start\n"

    ".global wallpaper_modder_start\n"
    ".type   wallpaper_modder_start, @object\n"
    ".align  16\n"
    "wallpaper_modder_start:\n"
    ".incbin \"../../../bootstrapper/assets/ps5-wallpaper-modd_v1.0-pizza-web-only.elf\"\n"
    "wallpaper_modder_end:\n"
    ".global wallpaper_modder_size\n"
    ".type  wallpaper_modder_size, @object\n"
    ".align  4\n"
    "wallpaper_modder_size:\n"
    ".int    wallpaper_modder_end - wallpaper_modder_start\n"

    ".global shadowmount_experimental_start\n"
    ".type   shadowmount_experimental_start, @object\n"
    ".align  16\n"
    "shadowmount_experimental_start:\n"
    ".incbin \"../../../bootstrapper/assets/shadowmountplus-experimental.elf\"\n"
    "shadowmount_experimental_end:\n"
    ".global shadowmount_experimental_size\n"
    ".type  shadowmount_experimental_size, @object\n"
    ".align  4\n"
    "shadowmount_experimental_size:\n"
    ".int    shadowmount_experimental_end - shadowmount_experimental_start\n"

    ".global ftpsrv_start\n"
    ".type   ftpsrv_start, @object\n"
    ".align  16\n"
    "ftpsrv_start:\n"
    ".incbin \"../../../bootstrapper/assets/ftpsrv-ps5.elf\"\n"
    "ftpsrv_end:\n"
    ".global ftpsrv_size\n"
    ".type  ftpsrv_size, @object\n"
    ".align  4\n"
    "ftpsrv_size:\n"
    ".int    ftpsrv_end - ftpsrv_start\n"

    ".global ps5debug_ng_start\n"
    ".type   ps5debug_ng_start, @object\n"
    ".align  16\n"
    "ps5debug_ng_start:\n"
    ".incbin \"../../../bootstrapper/assets/ps5debug-NG_v1.3.0.elf\"\n"
    "ps5debug_ng_end:\n"
    ".global ps5debug_ng_size\n"
    ".type  ps5debug_ng_size, @object\n"
    ".align  4\n"
    "ps5debug_ng_size:\n"
    ".int    ps5debug_ng_end - ps5debug_ng_start\n"

    ".global toolbox_shortcut_icon_start\n"
    ".type   toolbox_shortcut_icon_start, @object\n"
    ".align  16\n"
    "toolbox_shortcut_icon_start:\n"
    ".incbin \"../../../bootstrapper/assets/pizzahen_toolbox_icon.png\"\n"
    "toolbox_shortcut_icon_end:\n"
    ".global toolbox_shortcut_icon_size\n"
    ".type  toolbox_shortcut_icon_size, @object\n"
    ".align  4\n"
    "toolbox_shortcut_icon_size:\n"
    ".int    toolbox_shortcut_icon_end - toolbox_shortcut_icon_start\n"

    ".global toolbox_shortcut_param_start\n"
    ".type   toolbox_shortcut_param_start, @object\n"
    ".align  16\n"
    "toolbox_shortcut_param_start:\n"
    ".incbin \"../../../bootstrapper/assets/toolbox_shortcut_param.json\"\n"
    "toolbox_shortcut_param_end:\n"
    ".global toolbox_shortcut_param_size\n"
    ".type  toolbox_shortcut_param_size, @object\n"
    ".align  4\n"
    "toolbox_shortcut_param_size:\n"
    ".int    toolbox_shortcut_param_end - toolbox_shortcut_param_start\n"

    ".global toolbox_launcher_html_start\n"
    ".type   toolbox_launcher_html_start, @object\n"
    ".align  16\n"
    "toolbox_launcher_html_start:\n"
    ".incbin \"../../../bootstrapper/assets/toolbox_launcher.html\"\n"
    "toolbox_launcher_html_end:\n"
    ".global toolbox_launcher_html_size\n"
    ".type  toolbox_launcher_html_size, @object\n"
    ".align  4\n"
    "toolbox_launcher_html_size:\n"
    ".int    toolbox_launcher_html_end - toolbox_launcher_html_start\n"

    ".global debug_services_shortcut_param_start\n"
    ".type   debug_services_shortcut_param_start, @object\n"
    ".align  16\n"
    "debug_services_shortcut_param_start:\n"
    ".incbin \"../../../bootstrapper/assets/debug_services_shortcut_param.json\"\n"
    "debug_services_shortcut_param_end:\n"
    ".global debug_services_shortcut_param_size\n"
    ".type  debug_services_shortcut_param_size, @object\n"
    ".align  4\n"
    "debug_services_shortcut_param_size:\n"
    ".int    debug_services_shortcut_param_end - debug_services_shortcut_param_start\n"

    ".global debug_services_launcher_html_start\n"
    ".type   debug_services_launcher_html_start, @object\n"
    ".align  16\n"
    "debug_services_launcher_html_start:\n"
    ".incbin \"../../../bootstrapper/assets/debug_services_launcher.html\"\n"
    "debug_services_launcher_html_end:\n"
    ".global debug_services_launcher_html_size\n"
    ".type  debug_services_launcher_html_size, @object\n"
    ".align  4\n"
    "debug_services_launcher_html_size:\n"
    ".int    debug_services_launcher_html_end - debug_services_launcher_html_start\n"

    ".global fps_prx_start\n"
    ".type   fps_prx_start, @object\n"
    ".align  16\n"
    "fps_prx_start:\n"
    ".incbin \"../../../bootstrapper/assets/fps.prx\"\n"
    "fps_prx_end:\n"
    ".global fps_prx_size\n"
    ".type  fps_prx_size, @object\n"
    ".align  4\n"
    "fps_prx_size:\n"
    ".int    fps_prx_end - fps_prx_start\n"
);
