from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def rd(rel): return (ROOT/rel).read_text(errors='ignore')
checks=[]
def ok(name, cond):
    checks.append((name,bool(cond)))
    print(f"{name}={'PASS' if cond else 'FAIL'}")
app=rd('Source Code/daemon/source/app_plugins.cpp')
mono=rd('Source Code/shellui/src/MonoUtils.cpp')
hook=rd('Source Code/shellui/src/HookFunctions.cpp')
build=rd('build_pizzahen_multisdk.sh')
cm=rd('Source Code/unpacker/CMakeLists.txt')
doc=rd('FIX45_PLUGIN_MANAGER_LIFECYCLE.txt')
selector=rd('Source Code/bootstrapper/assets/kstuff_selector.html')
ok('FIX45_TARGET','PIZZA-HEN-v0.1-FIX45-PLUGIN-MANAGER-LIFECYCLE.elf' in cm)
ok('FIX45_MANAGER_TITLE','PIZZA HEN App Plugin Manager *BETA*' in mono)
ok('FIX45_PRIMARY_CONFIG','/data/PIZZA_HEN/plugins/apps/plugins.ini' in app and '/data/PIZZA_HEN/plugins/apps/plugins.ini' in mono)
ok('FIX45_SHELL_VIEW_FALLBACK','/user/data/PIZZA_HEN/plugins/apps/plugins.ini' in mono and 'resolve_app_plugins_config_path' in mono)
ok('FIX45_STATUS_FILE','/data/PIZZA_HEN/runtime/app_plugins_status.txt' in app and 'read_app_plugin_runtime_status' in mono)
ok('FIX45_ATOMIC_STATUS','atomic_write_text' in app and 'rename(tmp.c_str(), path)' in app)
ok('FIX45_STATUS_WRITE_DEDUP','g_last_published_status' in app and 'text == g_last_published_status' in app)
ok('FIX45_RUNTIME_FIELDS',all(x in app for x in ['state=','title_id=','configured=','armed=','loaded=','last_result=']))
ok('FIX45_SESSION_RESET','application closed; clearing session state' in app and 'PID change detected' in app)
ok('FIX45_SUCCESS_ONLY_DEDUP','Record only successful loads' in app and 'loaded_paths.push_back' in app)
ok('FIX45_RETRY_FAILURE','will retry while app remains active' in app)
ok('FIX45_CONFIG_RUNTIME_SEPARATE','saved autoload state and live runtime state are tracked separately' in mono)
ok('FIX45_ARMED_WORDING','ARMED for autoload' in mono and 'DISARMED' in mono)
ok('FIX45_NO_FAKE_HOT_UNLOAD','plugin_stop' not in app and 'does not fake etaHEN 2.6B plugin_stop behavior' in doc)
ok('FIX45_PAYLOAD_MANAGER_REFERENCE','PS5 Payload Manager 0.5.1' in doc and 'behavioral' in doc and 'reference' in doc)
ok('FIX45_MULTI_SDK',all(x in build for x in ['PIZZA_HEN_SDK','PS5_PAYLOAD_SDK','PS5SDK','PAYLOAD_SDK','PIZZA_HEN_TOOLCHAIN_FILE']))
ok('FIX45_SELECTOR_PRESERVED','KStuff Lite 1.09' in selector and 'KStuff DR 1.2' in selector)
ok('FIX45_ITEMZFLOW_PRESERVED','launch_pizzahen_backend("ITEM00001", "Game Manager")' in hook)
failed=[n for n,v in checks if not v]
if failed: raise SystemExit('FIX45_STATIC_FAIL='+','.join(failed))
print(f'FIX45_STATIC={len(checks)}/{len(checks)} PASS')
