from pathlib import Path
root=Path(__file__).resolve().parents[1]
def rd(rel): return (root/rel).read_text(errors='ignore')
main=rd('Source Code/bootstrapper/source/main.cpp')
daemon_c=rd('Source Code/bootstrapper/source/daemon.c')
cmake=rd('Source Code/unpacker/CMakeLists.txt')
bcmake=rd('Source Code/bootstrapper/CMakeLists.txt')
xml=rd('Source Code/shellui/assets/etaHEN_toolbox.xml')
hook=rd('Source Code/shellui/src/HookFunctions.cpp')
mono=rd('Source Code/shellui/src/MonoUtils.cpp')
util=rd('Source Code/util/source/main.cpp')
dmsg=rd('Source Code/daemon/source/msg.cpp')
checks=[]
def ok(n,c):
 print(f'{n}={"PASS" if c else "FAIL"}'); checks.append((n,bool(c)))
ok('FIX30_TARGET','PIZZA-HEN-v0.1-FIX45-PLUGIN-MANAGER-LIFECYCLE.elf' in cmake)
d6=main.index('PIZZA HEN D6: full automatic post-ShadowMount payload chain PASS')
utilpos=main.index('etaHEN Utility Daemon',d6)
segment=main[d6:utilpos]
ok('NO_D6_EARLY_RETURN','return 0;' not in segment)
ok('UTIL_DAEMON_REACHABLE','etaHEN Utility Daemon' in main and 'elfldr_spawn' in main[utilpos-150:utilpos+100])
ok('MAIN_DAEMON_REACHABLE','etaHEN Critical services' in main)
ok('PLUGIN_RUNTIME_REACHABLE','find_plugin_files()' in main and 'load_plugin(' in main)
ok('PKG_INSTALLER','id_game_package_installer' in xml)
ok('CUSTOM_BACKGROUND_PKG','id_game_custom_package_installer' in xml)
ok('PLUGINS_PAYLOADS','Plugins / Payload ELFs' in xml)
ok('CHEATS_FULL_LABEL','Cheats — Unified Repository' in xml)
ok('REMOTE_PLAY','Remote Play' in xml)
ok('EXTERNAL_HDD','id_external_hdd' in xml)
ok('TESTKIT','id_testkit_menu' in xml)
ok('KSTUFF_CONTROL','id_kstuff_opts' in xml and 'id_enable_kstuff_on_close' in xml)
ok('OVERLAY','id_overlay_opts' in xml and 'id_overlay_fps' in xml)
ok('CONTROLLER_SHORTCUTS','id_shortcuts' in xml and 'id_toolbox_shortcut' in xml)
ok('WEBMAN','id_ps5_backups' in xml)
ok('CUSTOM_GAME_OPTIONS','id_custom_game_opts' in xml)
ok('DISPLAY_TIDS','id_disp_titleids' in xml)
ok('HOMEBREW_STORE','id_download_store' in xml)
ok('REST_MODE','id_rest_mode' in xml)
ok('BLURAY','id_licenseactivation' in xml)
ok('AUTO_EJECT','id_auto_eject' in xml)
ok('DPI','id_dpi_service' in xml)
ok('DPIV2','id_DPI_v2_service' in xml)
ok('KLOG','id_klog_service' in xml)
ok('DATA_SANDBOX','id_data_sb' in xml)
ok('LEGACY_PS5DEBUG_UI_REMOVED','id_sistro_ps5debug' not in xml)
ok('DISCORD_UI','id_discord_rpc_service' in xml and 'global_conf.discord_rpc' in hook)
ok('DISCORD_CONFIG','discord_rpc=' in rd('Source Code/shellui/src/MonoUtils.cpp'))
ok('ITEMZFLOW','Itemzflow' in xml or 'Itemzflow' in main)
ok('UPDATE_BLOCKER','unmount("/update"' in main)
ok('GAME_DUMPER','id_activate_dumper' in hook and 'Launch_Dumper' in hook)
ok('CUSTOM_DELETE','★ Delete' in hook)
ok('CHEAT_UNIFIED',all(x in rd('Source Code/util/source/msg.cpp') for x in ['TeeKay87/HEN-Cheats-Collection','etaHEN/PS5_Cheats','GoldHEN/GoldHEN_Cheat_Repository','RDX-Sci01/HEN-PPSA-Cheats']))
ok('SHORTCUT_TITLE','PZHN00001' in main and 'PZHN00001' in rd('Source Code/bootstrapper/assets/toolbox_shortcut_param.json'))
ok('SHORTCUT_EMBED',all(x in daemon_c for x in ['toolbox_shortcut_icon_start','toolbox_shortcut_param_start','toolbox_launcher_html_start']))
ok('SHORTCUT_INSTALL_GUARD','shortcut_needs_update' in main and '.pizzahen_media_registered' in main and 'registration marker current' in main)
ok('SHORTCUT_APPINST','sceAppInstUtilAppInstallTitleDir' in main and 'SceAppInstUtil' in bcmake)
ok('SHORTCUT_WEB_LAUNCHER','pizzahen-toolbox-open.elf' in rd('Source Code/bootstrapper/assets/toolbox_launcher.html') and 'ItemzLaunchByUri("pssettings:play?mode=settings&function=debug_settings")' in dmsg)
ok('SHORTCUT_LOCAL_WEBSRV','127.0.0.1:8080' in rd('Source Code/bootstrapper/assets/toolbox_shortcut_param.json'))
ok('LEGACY_FTP_DEFAULT_OFF','bool FTP = false' in rd('Source Code/shellui/include/HookedFuncs.hpp') and 'Settings.FTP", "0"' in mono and 'global_conf.FTP = false' in util and 'FTP=0' in dmsg)
ok('EXTERNAL_FTP_PRESERVED','wait_for_local_ftpsrv' in main and '2121' in main)
ok('PS5DEBUG_NG_PRESERVED','wait_for_local_ps5debug_ng' in main and '744' in main)
ok('SHADOW_PRESERVED','shadowmount_start' in main and 'ShadowMountPlus 1.6beta16' in main)
ok('SELECTOR_PRESERVED','start_browser_kstuff_selector' in main and 'kstuff-lite-1.09' in main and 'kstuff-dr-1.2' in main)
ok('QUIET_FINAL','PIZZA HEN E6: complete Toolbox runtime' in main and 'notify("PIZZA HEN ready")' not in main)
ok('MATRIX_PRESENT',(root/'FIX30_FUNCTION_MATRIX.txt').exists())
failed=[n for n,c in checks if not c]
if failed: raise SystemExit('FIX30_STATIC_FAIL='+','.join(failed))
print(f'FIX30_STATIC={len(checks)}/{len(checks)} PASS')
