 __asm__(


    ".global ps5debug_start\n"
	".type   ps5debug_start, @object\n"
	".align  16\n"
	"ps5debug_start:\n"
    	".incbin \"../../../daemon/assets/ps5debug.elf\"\n"
	"ps5debug_end:\n"
	    ".global ps5debug_size\n"
	    ".type   ps5debug_size, @object\n"
	    ".align  4\n"
	"ps5debug_size:\n"
    	".int    ps5debug_end - ps5debug_start\n"


	".global shellui_elf_start\n"
	".type   shellui_elf_start, @object\n"
	".align  16\n"
	"shellui_elf_start:\n"
    	".incbin \"../../../daemon/assets/shellui.elf\"\n"
	"shellui_elf_end:\n"
	    ".global shellui_elf_size\n"
	    ".type   shellui_elf_size, @object\n"
	    ".align  4\n"
	"shellui_elf_size:\n"
    	".int    shellui_elf_end - shellui_elf_start\n"

	".global fps_elf_start\n"
	".type   fps_elf_start, @object\n"
	".align  16\n"
	"fps_elf_start:\n"
    	".incbin \"../../../daemon/assets/fps_elf.elf\"\n"
	"fps_elf_end:\n"
	    ".global fps_elf_size\n"
	    ".type   fps_elf_size, @object\n"
	    ".align  4\n"
	"fps_elf_size:\n"
    	".int    fps_elf_end - fps_elf_start\n"


    ".global pizzahen_kstuff_toggle_1_start\n"
    ".type   pizzahen_kstuff_toggle_1_start, @object\n"
    ".align  16\n"
    "pizzahen_kstuff_toggle_1_start:\n"
        ".incbin \"../../../daemon/assets/kstuff-toggle-1.elf\"\n"
    "pizzahen_kstuff_toggle_1_end:\n"
    ".global pizzahen_kstuff_toggle_1_size\n"
    ".type   pizzahen_kstuff_toggle_1_size, @object\n"
    ".align  4\n"
    "pizzahen_kstuff_toggle_1_size:\n"
        ".int    pizzahen_kstuff_toggle_1_end - pizzahen_kstuff_toggle_1_start\n"

    ".global pizzahen_kstuff_toggle_2_start\n"
    ".type   pizzahen_kstuff_toggle_2_start, @object\n"
    ".align  16\n"
    "pizzahen_kstuff_toggle_2_start:\n"
        ".incbin \"../../../daemon/assets/kstuff-toggle-2.elf\"\n"
    "pizzahen_kstuff_toggle_2_end:\n"
    ".global pizzahen_kstuff_toggle_2_size\n"
    ".type   pizzahen_kstuff_toggle_2_size, @object\n"
    ".align  4\n"
    "pizzahen_kstuff_toggle_2_size:\n"
        ".int    pizzahen_kstuff_toggle_2_end - pizzahen_kstuff_toggle_2_start\n"

    ".global pizzahen_kstuff_toggle_3_start\n"
    ".type   pizzahen_kstuff_toggle_3_start, @object\n"
    ".align  16\n"
    "pizzahen_kstuff_toggle_3_start:\n"
        ".incbin \"../../../daemon/assets/kstuff-toggle-3.elf\"\n"
    "pizzahen_kstuff_toggle_3_end:\n"
    ".global pizzahen_kstuff_toggle_3_size\n"
    ".type   pizzahen_kstuff_toggle_3_size, @object\n"
    ".align  4\n"
    "pizzahen_kstuff_toggle_3_size:\n"
        ".int    pizzahen_kstuff_toggle_3_end - pizzahen_kstuff_toggle_3_start\n"

    ".global pizzahen_klogsrv_start\n"
    ".type   pizzahen_klogsrv_start, @object\n"
    ".align  16\n"
    "pizzahen_klogsrv_start:\n"
        ".incbin \"../../../daemon/assets/klogsrv-ps5.elf\"\n"
    "pizzahen_klogsrv_end:\n"
    ".global pizzahen_klogsrv_size\n"
    ".type   pizzahen_klogsrv_size, @object\n"
    ".align  4\n"
    "pizzahen_klogsrv_size:\n"
        ".int    pizzahen_klogsrv_end - pizzahen_klogsrv_start\n"

    ".global pizzahen_fan_target_65c_start\n"
    ".type   pizzahen_fan_target_65c_start, @object\n"
    ".align  16\n"
    "pizzahen_fan_target_65c_start:\n"
        ".incbin \"../../../daemon/assets/fan_target_65c.elf\"\n"
    "pizzahen_fan_target_65c_end:\n"
    ".global pizzahen_fan_target_65c_size\n"
    ".type   pizzahen_fan_target_65c_size, @object\n"
    ".align  4\n"
    "pizzahen_fan_target_65c_size:\n"
        ".int    pizzahen_fan_target_65c_end - pizzahen_fan_target_65c_start\n"

    ".global pizzahen_fan_target_70c_start\n"
    ".type   pizzahen_fan_target_70c_start, @object\n"
    ".align  16\n"
    "pizzahen_fan_target_70c_start:\n"
        ".incbin \"../../../daemon/assets/fan_target_70c.elf\"\n"
    "pizzahen_fan_target_70c_end:\n"
    ".global pizzahen_fan_target_70c_size\n"
    ".type   pizzahen_fan_target_70c_size, @object\n"
    ".align  4\n"
    "pizzahen_fan_target_70c_size:\n"
        ".int    pizzahen_fan_target_70c_end - pizzahen_fan_target_70c_start\n"

    ".global pizzahen_fan_target_75c_start\n"
    ".type   pizzahen_fan_target_75c_start, @object\n"
    ".align  16\n"
    "pizzahen_fan_target_75c_start:\n"
        ".incbin \"../../../daemon/assets/fan_target_75c.elf\"\n"
    "pizzahen_fan_target_75c_end:\n"
    ".global pizzahen_fan_target_75c_size\n"
    ".type   pizzahen_fan_target_75c_size, @object\n"
    ".align  4\n"
    "pizzahen_fan_target_75c_size:\n"
        ".int    pizzahen_fan_target_75c_end - pizzahen_fan_target_75c_start\n"

    ".global pizzahen_fan_target_80c_start\n"
    ".type   pizzahen_fan_target_80c_start, @object\n"
    ".align  16\n"
    "pizzahen_fan_target_80c_start:\n"
        ".incbin \"../../../daemon/assets/fan_target_80c.elf\"\n"
    "pizzahen_fan_target_80c_end:\n"
    ".global pizzahen_fan_target_80c_size\n"
    ".type   pizzahen_fan_target_80c_size, @object\n"
    ".align  4\n"
    "pizzahen_fan_target_80c_size:\n"
        ".int    pizzahen_fan_target_80c_end - pizzahen_fan_target_80c_start\n"

    ".global pizzahen_fan_target_85c_start\n"
    ".type   pizzahen_fan_target_85c_start, @object\n"
    ".align  16\n"
    "pizzahen_fan_target_85c_start:\n"
        ".incbin \"../../../daemon/assets/fan_target_85c.elf\"\n"
    "pizzahen_fan_target_85c_end:\n"
    ".global pizzahen_fan_target_85c_size\n"
    ".type   pizzahen_fan_target_85c_size, @object\n"
    ".align  4\n"
    "pizzahen_fan_target_85c_size:\n"
        ".int    pizzahen_fan_target_85c_end - pizzahen_fan_target_85c_start\n"

    ".global pizzahen_cheatrunner_start\n"
    ".type   pizzahen_cheatrunner_start, @object\n"
    ".align  16\n"
    "pizzahen_cheatrunner_start:\n"
        ".incbin \"../../../bin/CheatRunner.elf\"\n"
    "pizzahen_cheatrunner_end:\n"
    ".global pizzahen_cheatrunner_size\n"
    ".type   pizzahen_cheatrunner_size, @object\n"
    ".align  4\n"
    "pizzahen_cheatrunner_size:\n"
        ".int    pizzahen_cheatrunner_end - pizzahen_cheatrunner_start\n"

    ".global pizzahen_phu_overlay_start\n"
    ".type   pizzahen_phu_overlay_start, @object\n"
    ".align  16\n"
    "pizzahen_phu_overlay_start:\n"
        ".incbin \"../../../daemon/assets/pizza_overlay_phu_fw1220plus.elf\"\n"
    "pizzahen_phu_overlay_end:\n"
    ".global pizzahen_phu_overlay_size\n"
    ".type   pizzahen_phu_overlay_size, @object\n"
    ".align  4\n"
    "pizzahen_phu_overlay_size:\n"
        ".int    pizzahen_phu_overlay_end - pizzahen_phu_overlay_start\n"


);

// PIZZA HEN v0.1: the upstream source archive does not ship the app-dumper ELF.
// Keep the ABI symbols but advertise a zero-sized payload so callers can fail safely.
#include <stdint.h>
uint8_t dumper_elf_start[1] = {0};
const unsigned int dumper_elf_size = 0;
